### ISSUE TITLE
Semi-tabbed layout is not restoring

### ISSUE THREAD

**Issue by eater** [klaxalk/i3-layout-manager#11]
I have a workspace with a vertically oriented monitor. On top is a tabbed container, and below that a different container. Here's the json: http://paste.ubuntu.com/p/hkdpgNVrDm/

I can't get it to restore that layout.

**Comment by klaxalk** [comment]
Sorry for the delay, I had a stream of nasty deadlines. Right now, I am not able to reproduce the issue. Could you please test whether it still persists? If so, could you send me a screenshot of your layout?

**Comment by eater** [comment]
Yes, it still persists with the latest commit. Attaching a screenshot of the latest layout I tried: three vertically tiled containers, two of which are internally tabbed.
![tabbedlayout](https://user-images.githubusercontent.com/106199/59209405-3fd8fe80-8b79-11e9-8c80-dc2828a43641.png)

When I load the saved layout, it just puts everything in a single tabbed container.

**Comment by klaxalk** [comment]
I made some updates that could fix it. Pls try again, and reopen the issue if it persists.
