### ISSUE TITLE
Layout doesn't save [?]

### ISSUE THREAD

**Issue by h8ed** [klaxalk/i3-layout-manager#12]
First off, I would like to say I think this is a wonderful thing. The i3 tile layout system (though it's not made specifically for such a thing) is overly complicated.

However, I can't really get it to work. No matter what options I give it, activating my saved layout always orders all my windows side by side (default i3 function). I'm trying to save a master & stack sort of layout like the default in wm's like dwm, xmonad, and qtile. Am I doing something wrong? I have a lot of work put into my i3 config, and I wouldn't want to switch window managers for something as simple as not being able to set tile layouts.

**Comment by klaxalk** [comment]
Hey, thanks. Could you send an example of your saved layout? They are located in ~/.layouts/

**Comment by klaxalk** [comment]
I made some updates that could fix it. Pls try again, and reopen the issue if it persists, and please provide more info.
