### ISSUE TITLE
Use xdg-user-dirs instead of ~

### ISSUE THREAD

**Issue by fleaz** [klaxalk/i3-layout-manager#15]
Hi,

to be more in line with established defaults (and to keep my homedir clean ;) ) it would be cool if i3-layout-maanger would stick to the folders defined by `xdg-user-dirs` . Currently the `$LAYOUT_PATH` is hardcoded to `~/.layouts`, but using e.g. `$XDG_CONFIG_HOME/i3-layout-manager` would be more sane imho to store the layout files

A detailed description of the directores can be found here: [freedesktop.org](https://www.freedesktop.org/wiki/Software/xdg-user-dirs/)

Best,
Felix

**Comment by klaxalk** [comment]
Hey, sure, will do. Thanks.

**Comment by klaxalk** [comment]
In the end, when $XDG_CONFIG_HOME exists, the layouts are saved to $XDG_CONFIG_HOME/i3-layout-manager/layouts. Otherwise, the ~/.layouts is used. The variable is not defined on my Ubuntu...
