### ISSUE TITLE
Error when trying to start terminal application

### ISSUE THREAD

**Issue by dinotheextinct** [klaxalk/i3-layout-manager#16]
`exec --no-startup-id "i3-msg 'workspace $workspace10; append_layout /home/dino/.layouts/layout-MUSIC.json'"`

ERROR: Layout file is invalid: found an empty swallow definition.
ERROR: JSON parsing error: parse error: client cancelled parse via callback return value
          ncmpcpp\\ 0\\.8\\.2$"        }     ],     "type": "con" }  {
                     (right here) ------^

**Comment by dinotheextinct** [comment]
I tried with class or instance and got the same problem.

**Comment by klaxalk** [comment]
Hey, this could happen when the name (class, title, etc.) of the window is somehow weird. In this case, it looks like the ncmpcpp window contains space and the version number and it was backslashed automatically. The parser might not like it. Try to fix it by manually editing the layout file. Find the line and modify the text used for matching to something different, e.g., `^.*ncmpcpp.*$`. Those matching rules are regular expressions.

**Comment by dinotheextinct** [comment]
Still gives me the same error:
https://i.imgur.com/Xx3dXPW.png

**Comment by klaxalk** [comment]
Hey, I fixed some bugs, maybe now it could work. If not, let me know if you use vim or nvim and what version of i3 do you have.
