### ISSUE TITLE
Doesnt save?

### ISSUE THREAD

**Issue by thepenguinthatwants** [klaxalk/i3-layout-manager#17]
I tried this but seems like archlinux i3 it doesnt seem to work.

```
> [
> 	Can't locate AnyEvent/I3.pm in @INC (you may need to install the AnyEvent::I3 module) (@INC contains: /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at /usr/bin/i3-save-tree line 19.
> 	BEGIN failed--compilation aborted at /usr/bin/i3-save-tree line 19.
> ]
> }
> ]
```

**Comment by klaxalk** [comment]
Hey, that seems beyond my scope. I can suggest debugging the i3-save-tree
directly, but it looks like there is something missing on your end.

út 14. 5. 2019 v 16:43 odesílatel thepenguinthatwants <
notifications@github.com> napsal:

**Comment by GotekSC** [comment]
Installing perl-anyevent-i3 solved this problem for me.

**Comment by Griatch** [comment]
For Linux Mint/Ubuntu, this was needed for me (without `indent` the layout file is empty, without the `anyevent` lib, the error above is seen): 

```
sudo apt install indent libanyevent-i3-perl
```

Seems like the requirement instructions need to be updated.

**Comment by klaxalk** [comment]
Thanks, I have updated them.

**Comment by nisnevich** [comment]
> Installing `perl-anyevent-i3` from the manjaro repos (which mostly mirror the archlinux ones) solved this problem for me.

Thanks! It helped me also.
