### ISSUE TITLE
Empty layout files

### ISSUE THREAD

**Issue by heyyzoeyy** [klaxalk/i3-layout-manager#18]
In ~/.layouts, all the json files are completely empty, 0B. This is why my layout does not get restored. How do I get them to save?

**Comment by Giorgiofox** [comment]
Me too: 
the content of all my json file is only:
```
[root@x1arch .layouts]# cat /user/.layouts/layout-PIPPO.json 
[
]
}
]
```
thanks
Giorgio

**Comment by Griatch** [comment]
Same for me. All layout files come out empty.

**Comment by Griatch** [comment]
Update - there seems to be some dependencies not listed, notably the `indent` and `anyevent` i3 module are needed. This resolved it for me: 
```
sudo apt install indent libanyevent-i3-perl
```

**Comment by klaxalk** [comment]
Thanks! Someone already fixed that.
