### ISSUE TITLE
Loading previously saved layout close all programs

### ISSUE THREAD

**Issue by Migacz85** [klaxalk/i3-layout-manager#20]
I ends with all programs clossed when I'm calling the script in stacked mode. Window on window. Somebody experience same thing?

**Comment by Migacz85** [comment]
I tested this in different circumnstances. And this look like that stacked mode is not a direct issue. Sometimes the layout is perfectly loaded sometimes is closing ALL programs. Which as you can expect can be really frustrating. 

This is really boggling my mind. How I can debug it to find what is the root of that bug?

**Comment by klaxalk** [comment]
Hey, it sometimes happens to me aswell when the windows somehow change on their own during the unmapping-and-mapping from the workspace. I mean that they e.g. spawn new floating subwindows or change from tiled to floating. I should at least test the results of the `xdotool windowunmap` and log it, so we could get to the root of it.

**Comment by klaxalk** [comment]
I sprinkled in some log prints. So when this happens again, pls post the /tmp/i3_layout_manager.txt file.

**Comment by Migacz85** [comment]
This issue should have the highest priority

**Comment by klaxalk** [comment]
I have found a weird bug with x-windows, their xdotool sometimes returns inconsistent responses. I think it should fix this.

**Comment by Migacz85** [comment]
Is that issue was resolved?

**Comment by klaxalk** [comment]
Hey, ye I think it is solved. I sometimes still experience similar problems but it is very rare and hard to reproduce. I also think it has something to do with a race condition of new windows being opened while loading the layout.

**Comment by Migacz85** [comment]
This is a critical issue - if you will lose your work. Maybe some automated
test that is doing layout change 30 times in a row or something like that
can reproduce the problem? So it would be easier to make it 100% robust?
