### ISSUE TITLE
The layout manager does not handle parentheses correctly

### ISSUE THREAD

**Issue by jazzpi** [klaxalk/i3-layout-manager#24]
When the window title contains parentheses and I try to match the title, the `swallows` part will contain the unescaped parentheses. This then doesn't restore the windows properly (which I guess is due to the parentheses being interpreted as a capture group).

**Comment by klaxalk** [comment]
Ye, that will be a problem. I could make it work, but I would rather not
use parentheses in the names...

po 9. 12. 2019 v 14:58 odesílatel Jasper v. B. <notifications@github.com>
napsal:
