### ISSUE TITLE
Lost Chrome search bar in full screen 

### ISSUE THREAD

**Issue by hossein-rasi** [klaxalk/i3-layout-manager#25]
Hey there. That would be great if you can help me. I tried to use this layout manager but not only it didn't restore properly ( only loads black screen windows) but also I have lost Google Chrome's search bar when I tied to full screen it. As a matter of fact, it is really painful and that would be great if you can give me some hint to fix it. Thanks!

**Comment by klaxalk** [comment]
I made some changes which could relate to that, however, Chrome losing its search bar is nothing I can influence. It might be that the browser was incorrectly closed and it lost its settings, but I don't know. Never happened to me. But I suppose you fixed that since.
