### ISSUE TITLE
Not swallowing when "instance": ""

### ISSUE THREAD

**Issue by alexkutzke** [klaxalk/i3-layout-manager#39]
Hey! First, thanks for your great job with this project.

I don't know exactly why, on the "match all" workflow, my windows are not getting swallowed by placeholders. 
At least, when the swallow rule is set to `"instance": ""`.

To correct this, I had to change the rules to: `"instance": "^.+$"`

My i3 version: 4.19.1 (2021-02-01)

**Comment by wbmnfktr** [comment]
Your issue helped me to understand why it wasn't working.
Therefore I now changed line 360 which makes it work again. 

`$VIM_BIN $HEADLESS -nEs -u NONE -c '%g/instance/norm ^dW3f"di"i^.+$' -c "wqa" -- "$LAYOUT_FILE"
`

There might be a more elegant version but for now this will do the trick.

Tested on i3 version 4.19.1-183

**Comment by klaxalk** [comment]
That is a good fix, I push it to master. Thx!
