### ISSUE TITLE
Floating window position doesn't restore

### ISSUE THREAD

**Issue by eater** [klaxalk/i3-layout-manager#6]
I have three floating windows that I want on the same workspace at the same time. I arrange them with the mouse and save the layout. Then I restore the layout, and it centers them all (and also changes their sizes slightly).

The .json file looks like it's saving the right info. How can I debug this?

**Comment by klaxalk** [comment]
Hey, can you share the resulting .json? It might be a bug. Or it might be, that the application, which spawns the windows, does not react well to _unmapping_ and _mapping_ the windows back (as typically python plots do).

**Comment by klaxalk** [comment]
Are the original windows the only windows in the workspace while being floting? I am able to reproduce a problem (slightly different, the windows loos the floating properties) by doing that. I will look into my bug and let's see whether it will fix yours.

**Comment by klaxalk** [comment]
Hey, sorry for the delay. I had a stream of nasty deadlines. I am looking back into this problem and I can't reproduce it anymore. Maybe something changed... Could you please test it again? Let me know if the problem is still relevant.

**Comment by klaxalk** [comment]
I think I managed to fix it. There was a special case in nvim where it does not correctly interpret some commands in the headless mode. However, take the floating window support with a grain of salt. It only works if the program is not doing any "splash" screens or window initialization. E.g, the Thunar does not work. It eats up the prepared placeholder but then it reinitializes and loses the floating property. I can't do anything about it.
