### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mg979** [klaxalk/i3-layout-manager#8]
OS: debian stable (i3wm version 4.13)

If I save a layout with `./layout_manager.sh` from the cli, I enter a name in rofi, but I get `/bin/bash: indent: command not found`.
The resulting json file is empty. I can't find this `indent` command in the bash script.

**Comment by gservat** [comment]
I think `vim` internally uses `indent`. If you're using ubuntu, try `apt-get install -y indent`.

**Comment by mg979** [comment]
Thanks, not mentioned in the requirements, I'll try again.

**Comment by mg979** [comment]
I get this now (in a saved layout json)
```
 1   │ [
   2   │     Can't locate AnyEvent/I3.pm in @INC (you may need to install the AnyEvent::I3 modu
       │ le) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/s
       │ hare/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64
       │ -linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-lin
       │ ux-gnu/perl-base) at /usr/bin/i3-save-tree line 19.
   3   │     BEGIN failed--compilation aborted at /usr/bin/i3-save-tree line 19.
   4   │ ]
   5   │ }
   6   │ ]
```

**Comment by klaxalk** [comment]
Hey, sorry for the delay, I had a stream of big deadlines. This looks like the i3-save-tree command, provided by i3, does not work. I can't help much with that, try to debug it manually.
